services:
  # 1. Managed PostgreSQL Database
  - type: postgres
    name: ev-charging-db
    databaseName: ev_charging_db
    user: thananonchounudom
    region: singapore # Choose the region closest to you
    plan: free # Use 'free' for testing, 'standard' for production

  # 2. Web Service (Backend + Frontend)
  - type: web
    name: ev-charging-web-app
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build && cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ev-charging-db
          property: connectionString
      - key: NODE_VERSION
        value: 18 # Specify Node.js version
      - key: PORT
        value: 5001
 

 