databases:
  - name: ev-charging-db
    databaseName: ev_charging_db
    region: singapore
    plan: free

services:
  - type: web
    name: ev-charging-web-app
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build && npm install --prefix server
    startCommand: node server/index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ev-charging-db
          property: connectionString
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production