databases:
  - name: ev-charging-db
    databaseName: ev_charging_db
    user: thananonchounudom
    region: singapore
    plan: free

services:
  - type: web
    name: ev-charging-web-app
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build && cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ev-charging-db
          property: connectionString
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 5001